/**
 * AUTO-EXTRACTED from the legacy public/index.html inline script.
 *
 * These objects are lifted verbatim so the migrated UI reports exactly the same
 * findings, remediation text, explainer copy and record-type colours as the app
 * they replace. Do not hand-edit: re-run scripts/extract-consts.cjs instead.
 *
 * Extracted: SEV_RANK, SEV_LABEL, TAB_CAT, CAT_LABEL, FINDING_META, EXPLAIN, TC
 */

export const SEV_RANK = { crit:0, high:1, med:2, low:3, good:4 };

export const SEV_LABEL = { crit:'Critical', high:'High', med:'Medium', low:'Low', good:'Pass' };

export const TAB_CAT = {
  dns:'core', whois:'core', geoip:'core', propagation:'core',
  ssl:'security', security:'security', headers:'security', csp:'security', dnssec:'security',
  'dnssec-chain':'security', ocsp:'security', hsts:'security', takeover:'security',
  emailsec:'email', mx:'email', mtasts:'email',
  ipv6:'network', trace:'network', ports:'network',
  http:'web', redirect:'web', tech:'web', cors:'web', robots:'web',
  ct:'intelligence', typosquat:'intelligence',
};

export const CAT_LABEL = { core:'Core / DNS', security:'Security', email:'Email', network:'Network', web:'Web', intelligence:'Intelligence' };

export const FINDING_META = {
  'ssl-expired':      { tab:'ssl', fix:'Renew the certificate with your CA or ACME client (e.g. certbot renew) and reload the web server.' },
  'ssl-expiring':     { tab:'ssl', fix:'Renew before expiry — or better, set up automatic renewal (Let’s Encrypt renews at 30 days remaining).' },
  'ssl-sha1':         { tab:'ssl', fix:'Reissue the certificate — every modern CA signs with SHA-256 by default.' },
  'ssl-sslv3':        { tab:'ssl', fix:'Disable SSLv3 in the server TLS config (it has been obsolete since 2015).' },
  'ssl-legacy-tls':   { tab:'ssl', fix:'Set the minimum TLS version to 1.2 in your server/CDN configuration.' },
  'ssl-no-tls13':     { tab:'ssl', fix:'Enable TLS 1.3 — supported by all maintained servers (nginx ≥1.13, OpenSSL ≥1.1.1).' },
  'ssl-vuln':         { tab:'ssl', fix:'Update the TLS library / server and disable the affected protocol or cipher.' },
  'ssl-good':         { tab:'ssl' },
  'spf-missing':      { tab:'emailsec', fix:'Publish a TXT record naming the servers allowed to send your mail, ending in -all.',
                        snippet:d=>`${d}. TXT "v=spf1 include:<your-mail-provider> -all"` },
  'dmarc-missing':    { tab:'emailsec', fix:'Publish a DMARC policy TXT record at _dmarc — start with p=quarantine and an aggregate-report address.',
                        snippet:d=>`_dmarc.${d}. TXT "v=DMARC1; p=quarantine; rua=mailto:dmarc@${d}"` },
  'dmarc-none':       { tab:'emailsec', fix:'Change p=none to p=quarantine (then p=reject once reports look clean).',
                        snippet:d=>`_dmarc.${d}. TXT "v=DMARC1; p=quarantine; rua=mailto:dmarc@${d}"` },
  'dmarc-pct':        { tab:'emailsec', fix:'Raise pct to 100 so the policy protects all mail.' },
  'dkim-missing':     { tab:'emailsec', fix:'Enable DKIM signing at your mail provider and publish the public key they give you at <selector>._domainkey.' },
  'email-good':       { tab:'emailsec' },
  'bl-listed':        { tab:'security', fix:'Visit each blacklist’s delisting page and request removal; find and stop the source of spam first.' },
  'bl-clean':         { tab:'security' },
  'dnssec-off':       { tab:'dnssec', fix:'Enable DNSSEC at your DNS host (usually one click), then publish the DS record at your registrar.' },
  'dnssec-incomplete':{ tab:'dnssec', fix:'Publish the DS record at your registrar to complete the chain of trust.' },
  'dnssec-good':      { tab:'dnssec' },
  'dnssecchain-broken':{ tab:'dnssec-chain', fix:'Re-sync the DS record at the parent with your current DNSKEY (re-publish after key rollovers).' },
  'takeover-found':   { tab:'takeover', fix:'Delete the dangling CNAME record, or re-claim the service it points to.' },
  'takeover-clean':   { tab:'takeover' },
  'ports-risky':      { tab:'ports', fix:'Firewall these ports to trusted IPs only (or bind the services to localhost/VPN).' },
  'ports-good':       { tab:'ports' },
  'headers-missing':  { tab:'headers', fix:'Add the header in your web server or CDN configuration.' },
  'headers-hsts':     { tab:'headers', fix:'Add the Strict-Transport-Security header so browsers always use HTTPS.',
                        snippet:()=>`Strict-Transport-Security: max-age=31536000; includeSubDomains` },
  'headers-good':     { tab:'headers' },
  'hsts-preload':     { tab:'hsts', fix:'Submit the domain at hstspreload.org — it already meets the requirements.' },
  'whois-expiring':   { tab:'whois', fix:'Renew the domain at your registrar and turn on auto-renew.' },
  'whois-good':       { tab:'whois' },
  'prop-inconsistent':{ tab:'propagation', fix:'If you changed DNS recently, wait for TTLs to expire; otherwise verify records at your DNS host.' },
  'prop-good':        { tab:'propagation' },
  'mx-none':          { tab:'mx', fix:'If this domain should receive email, add MX records at your DNS host. If not, this is fine.' },
  'mx-single':        { tab:'mx', fix:'Add a second MX record with a higher priority number as backup.' },
  'mx-nostarttls':    { tab:'mx', fix:'Enable STARTTLS on the mail server so inbound mail is encrypted in transit.' },
  'mx-good':          { tab:'mx' },
  'mtasts-missing':   { tab:'mtasts', fix:'Publish an _mta-sts TXT record plus the policy file at https://mta-sts.<domain>/.well-known/mta-sts.txt.',
                        snippet:d=>`_mta-sts.${d}. TXT "v=STSv1; id=${new Date().toISOString().slice(0,10).replace(/-/g,'')}01"` },
  'mtasts-testing':   { tab:'mtasts', fix:'Switch the policy file from mode: testing to mode: enforce once delivery reports look clean.' },
  'mtasts-good':      { tab:'mtasts' },
  'ocsp-nostapling':  { tab:'ocsp', fix:'Enable OCSP stapling in the web server (nginx: ssl_stapling on; — apache: SSLUseStapling on).' },
  'ocsp-good':        { tab:'ocsp' },
  'redirect-nohttps': { tab:'redirect', fix:'Add a permanent (301) redirect from http:// to https:// for every request.' },
  'redirect-long':    { tab:'redirect', fix:'Collapse the chain — redirect straight to the final URL in one hop.' },
  'redirect-good':    { tab:'redirect' },
  'csp-missing':      { tab:'csp', fix:'Start with a report-only policy, review the reports, then enforce.',
                        snippet:()=>`Content-Security-Policy: default-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'` },
  'csp-unsafe':       { tab:'csp', fix:'Replace unsafe-inline/unsafe-eval with nonces or hashes (add strict-dynamic for modern browsers).' },
  'csp-good':         { tab:'csp' },
  'cors-wide':        { tab:'cors', fix:'Never combine a wildcard origin with credentials — echo specific trusted origins instead.' },
  'ipv6-missing':     { tab:'ipv6', fix:'Add an AAAA record pointing at your server’s IPv6 address (most CDNs enable this with one toggle).' },
  'ipv6-good':        { tab:'ipv6' },
  'trace-unreachable':{ tab:'trace', fix:'Check that the server is up and that A/AAAA records point to the right address.' },
  'caa-missing':      { tab:'dns', fix:'Add a CAA record naming the only CA allowed to issue certificates for this domain.',
                        snippet:d=>`${d}. CAA 0 issue "letsencrypt.org"` },
  'dns-good':         { tab:'dns' },
  'typosquat-found':  { tab:'typosquat', fix:'Review who registered them; consider defensive registration of high-risk variants and takedown requests for active phishing.' },
  'typosquat-clean':  { tab:'typosquat' },
  'http-good':        { tab:'http' },
};

export const EXPLAIN = {
  dns: { title:'DNS records',
    what:'DNS records are the address book of your domain — they tell the internet where your website, email and other services live.',
    why:'Wrong or missing records mean visitors can’t reach your site or your email silently breaks.',
    expert:'Shows A/AAAA/MX/TXT/NS/CNAME/SOA/CAA/SRV/PTR from the selected resolver profile.' },
  whois: { title:'WHOIS / registration',
    what:'The public registration record for the domain: who registered it, through which registrar, and when it expires.',
    why:'If the registration lapses, the domain can be lost or bought by someone else — expiry is the single most catastrophic thing to miss.',
    expert:'RDAP is queried first (structured data), with legacy WHOIS as fallback.' },
  geoip: { title:'GeoIP',
    what:'Where in the world the server behind this domain is located, and which network/company operates it.',
    why:'Useful for latency, data-residency and spotting unexpected hosting changes.',
    expert:'Resolves the first A record and looks it up via ipwho.is.' },
  propagation: { title:'DNS propagation',
    what:'Checks whether major public DNS resolvers around the world all return the same answer for this domain.',
    why:'After you change DNS, some visitors can be sent to the old server for hours. Inconsistent answers can also indicate hijacking.',
    expert:'Queries Google, Cloudflare, Quad9, OpenDNS, Comodo, Level3, Verisign in parallel.' },
  ssl: { title:'SSL/TLS',
    what:'The certificate and encryption settings that put the padlock in the browser and keep traffic private.',
    why:'An expired certificate takes your site down with a scary browser warning; weak settings let attackers eavesdrop or tamper.',
    expert:'SSL-Labs-style grading: protocol support (SSLv3→TLS1.3), cipher/PFS analysis, chain validation with AIA fetching, known-vuln checks.' },
  security: { title:'the security overview',
    what:'A quick pass/fail across the most fundamental protections: SPF, DMARC, CAA, MX and blacklist status.',
    why:'These five basics stop the most common real-world attacks: email spoofing and rogue certificates.',
    expert:'Derived from DNS insights + DNSBL results; the deeper per-topic tabs have full detail.' },
  headers: { title:'security headers',
    what:'Extra instructions your website sends browsers, telling them to block common attack techniques.',
    why:'They are free, one-line protections against clickjacking, content-sniffing and downgrade attacks — most sites simply forget them.',
    expert:'Checks HSTS, CSP, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy and flags deprecated ones.' },
  csp: { title:'Content-Security-Policy',
    what:'A browser rule-set that says which scripts and resources are allowed to run on your pages.',
    why:'CSP is the strongest defence against XSS — injected malicious scripts simply refuse to run.',
    expert:'Grades directive quality; unsafe-inline/unsafe-eval and wildcards are penalized, nonce/strict-dynamic rewarded.' },
  dnssec: { title:'DNSSEC',
    what:'Cryptographic signatures on your DNS records, so resolvers can verify answers weren’t forged.',
    why:'Without it, attackers can poison DNS caches and silently redirect your visitors to fake servers.',
    expert:'Checks DNSKEY/DS/RRSIG presence and consistency.' },
  'dnssec-chain': { title:'the DNSSEC chain of trust',
    what:'DNSSEC only works if every level — root, TLD, and your zone — links its signatures correctly. This walks the whole chain.',
    why:'A broken link anywhere silently disables the protection (or worse, makes your domain unresolvable for validating resolvers).',
    expert:'Validates root → TLD → zone: DS at parent must match DNSKEY at child.' },
  ocsp: { title:'OCSP / revocation',
    what:'How browsers find out if your certificate has been cancelled (revoked) before its expiry date.',
    why:'If a certificate’s key leaks, revocation is the only kill-switch — and stapling makes checking it fast and private.',
    expert:'Checks OCSP responder presence, CRL distribution points and stapling support.' },
  hsts: { title:'HSTS preload',
    what:'A browser-built-in list of domains that must always use HTTPS — even on the very first visit.',
    why:'Being preloaded closes the one window (the first insecure request) where an attacker on public Wi-Fi can hijack visitors.',
    expert:'Checks the Strict-Transport-Security header (max-age ≥1y, includeSubDomains, preload) and Chrome preload list membership.' },
  takeover: { title:'subdomain takeover',
    what:'Looks for subdomains that point at cloud services (Heroku, S3, GitHub Pages…) which nobody claims anymore.',
    why:'Anyone can register the abandoned service name and serve their own content — phishing pages — under YOUR domain.',
    expert:'Detects dangling CNAMEs against known-fingerprint SaaS targets.' },
  emailsec: { title:'email authentication',
    what:'SPF, DKIM and DMARC — the three records that prove an email really came from your domain.',
    why:'Without them, anyone can send convincing fake mail as you (invoices, password resets), and your own mail lands in spam.',
    expert:'SPF policy strength, DMARC policy/pct/rua, DKIM selector discovery, BIMI bonus.' },
  mx: { title:'MX / SMTP',
    what:'The mail servers that receive email for this domain, and whether they accept encrypted delivery.',
    why:'A single mail server is a single point of failure; missing STARTTLS means mail to you can be read in transit.',
    expert:'Resolves MX records and probes each server’s SMTP banner + STARTTLS support.' },
  mtasts: { title:'MTA-STS & DANE',
    what:'Rules telling other mail servers to only deliver email to you over verified, encrypted connections.',
    why:'Ordinary email encryption is trivially stripped by an attacker in the middle — MTA-STS/DANE make the encryption mandatory.',
    expert:'Checks _mta-sts TXT + HTTPS policy file (mode enforce/testing) and TLSA records.' },
  ipv6: { title:'IPv6',
    what:'Whether the site is reachable over IPv6, the modern internet addressing standard.',
    why:'A growing share of users (especially mobile) are IPv6-first; without it they reach you via slower translation layers — or not at all.',
    expert:'AAAA presence, dual-stack, TLS handshake over v4 vs v6.' },
  trace: { title:'connectivity',
    what:'Basic reachability of the server: which IP addresses answer, over IPv4 and IPv6.',
    why:'If nothing answers here, everything else is moot — the host is down or firewalled.',
    expert:'A/AAAA resolution + reachability summary.' },
  ports: { title:'the port scan',
    what:'Knocks on the most common network "doors" (web, email, SSH, databases) to see which are open to the whole internet.',
    why:'Databases or remote-desktop ports open to the world are among the most exploited misconfigurations anywhere.',
    expert:'TCP connect scan of ~13 common ports, 2.5s timeout each.' },
  http: { title:'HTTP features',
    what:'How modern and efficient the web server setup is: HTTP/2/3, compression, and key headers.',
    why:'Modern protocols and compression make the site noticeably faster for every visitor — and Google ranks on speed.',
    expert:'Scores HTTP/2/3, brotli/gzip, HSTS, CSP, frame and referrer policies.' },
  redirect: { title:'the redirect chain',
    what:'What happens step-by-step when someone types your domain: every redirect hop until the final page.',
    why:'Sites that don’t immediately redirect to HTTPS leave visitors exposed; long chains slow down every first visit.',
    expert:'Follows up to the final hop recording status codes and timing.' },
  tech: { title:'the technology fingerprint',
    what:'The software visibly running the site: CMS, frameworks, hosting, analytics.',
    why:'Useful for audits — and a reminder of what an attacker can see: advertised software versions invite targeted exploits.',
    expert:'Passive fingerprinting from headers, cookies and HTML patterns.' },
  cors: { title:'CORS',
    what:'Rules controlling which OTHER websites are allowed to read data from this site inside a browser.',
    why:'An over-permissive policy can let any malicious site read your users’ private data using their own logged-in session.',
    expert:'Inspects Access-Control-Allow-Origin/Credentials/Methods responses.' },
  robots: { title:'robots.txt & sitemap',
    what:'The files that tell search engines what to index and where to find your pages.',
    why:'A broken robots.txt can accidentally hide your whole site from Google — or expose paths you meant to keep quiet.',
    expert:'Fetches /robots.txt and referenced sitemaps.' },
  ct: { title:'Certificate Transparency',
    what:'Public logs recording every certificate ever issued for your domain.',
    why:'If a certificate appears here that you didn’t request, someone else may be impersonating your domain.',
    expert:'Queries CT logs (crt.sh) for recent issuances.' },
  typosquat: { title:'typosquatting',
    what:'Checks whether look-alike misspellings of your domain (gooogle.com, githb.com…) are registered by someone.',
    why:'Registered typos are the raw material of phishing campaigns against your users and brand.',
    expert:'Generates common typo/homoglyph variants and checks registration.' },
};

export const TC = {
  A:    { bg:'rgba(99,102,241,.1)',    bd:'rgba(99,102,241,.32)',    fg:'#818cf8' },
  AAAA: { bg:'rgba(99,102,241,.1)',    bd:'rgba(99,102,241,.32)',    fg:'#818cf8' },
  MX:   { bg:'rgba(167,139,250,.1)', bd:'rgba(167,139,250,.32)', fg:'#a78bfa' },
  TXT:  { bg:'rgba(245,158,11,.1)',  bd:'rgba(245,158,11,.32)',  fg:'#f59e0b' },
  NS:   { bg:'rgba(16,185,129,.1)',  bd:'rgba(16,185,129,.32)',  fg:'#10b981' },
  CNAME:{ bg:'rgba(96,165,250,.1)',  bd:'rgba(96,165,250,.32)',  fg:'#60a5fa' },
  SOA:  { bg:'rgba(244,114,182,.1)', bd:'rgba(244,114,182,.32)', fg:'#f472b6' },
  CAA:  { bg:'rgba(251,146,60,.1)',  bd:'rgba(251,146,60,.32)',  fg:'#fb923c' },
  SRV:  { bg:'rgba(167,139,250,.1)', bd:'rgba(167,139,250,.32)', fg:'#a78bfa' },
  PTR:  { bg:'rgba(148,163,184,.1)', bd:'rgba(148,163,184,.32)', fg:'#94a3b8' },
};
